name: shareimage
description: A new Flutter project.
version: 0.0.1
author: Evgeny Vasilyev
homepage: https://github.com/Zeejfps/flutter_shareimage/blob/master/pubspec.yaml

flutter:
  plugin:
    androidPackage: com.ttuicube.shareimage
    pluginClass: ShareimagePlugin

dependencies:
  meta: ^1.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^2.2.3
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"